### ISSUE TITLE
`javascript-for-solid` docs say don't use `new`, then proceed to use `new`

### ISSUE THREAD

**Issue by mangelozzi** [solidjs/solid-docs-next#110]
https://docs.solidjs.com/how-to-guides/get-ready-for-solid/javascript-for-solid

> When first writing modern JavaScript you might be tempted to use one of these keywords:
> var, new, this, class

Then scroll down a little and it has an example with the `new` keyword:
```
const currentYear = new Date().getFullYear();
```

Its confusing, why use `new` after saying don't use it?

**Comment by Jutanium** [comment]
Yeah I'll take `new` out of the advice at the beginning; I stand by it when writing you _own_ Solid code, but it's misleading because you don't really have a choice when consuming others' code
