### ISSUE TITLE
Incorrect theme toggle icon is initially shown for dark-mode browsers

### ISSUE THREAD

**Issue by nizewn** [solidjs/solid-docs-next#120]
When visiting the docs for the first time (or in Incognito) with a browser that prefers dark color schemes, the page correctly uses the dark theme, but the toggle button/icon does not. You'd have to click the button twice to switch to the light theme.

I believe this is caused by the theme toggle button depending on the `mode` property in the config context which is initially set to `"none"`, since the button/icon only assumes the page is dark when `config().mode` is set to `"dark"`.

A possible solution for this would be to initially set `config().mode` to either `"light"` or `"dark"` only instead of `"none"`, depending on the browser's preferred color scheme.

**Comment by Jutanium** [comment]
Yes, thank you! Just rewrote this on another branch, will merge this week
