### ISSUE TITLE
Nested Routing demo doesn't show URL

### ISSUE THREAD

**Issue by redbar0n** [solidjs/solid-docs-next#134]
The Nested Routing demo:

https://docs.solidjs.com/start/core-concepts/routing-and-pages#nested-routing

> Let's consider a UI to help us out. Hover or tap each button to **see how each segment of the URL** maps to three things: a component layout, a JavaScript bundle, and a piece of data.

Some issues:

1. It wasn't obvious that it was a scrollable iFrame window. Not sure what 3 things you refer to in that entire page inside the iFrame.
2. The iFrame cannot be resized. It's frustrating. Especially if I'm supposed to find 3 specific things inside it.
3. The URL is not visible. So the demonstration fails.

**Comment by nksaraf** [comment]
This part is incomplete.. maybe shouldnt have merged... thanks for reporting!

**Comment by chaance** [comment]
It's an iframe pointing to a route from the Remix docs, from which these docs are directly copy/pasted without attribution. Perhaps you should reconsider that approach and remove the iframe altogether.
