### ISSUE TITLE
Some UI and colors issues

### ISSUE THREAD

**Issue by robin4a4** [solidjs/solid-docs-next#136]
I figured there are some minor issues with color accessibility (the white text on light blue background for active items in the menu does not clear every accessibility test for example). There are also things that are hard to read in the nav bar mainly because of spacing and separators issues. I created a [Figma file](https://www.figma.com/file/33g5ZOPX2aWDg3uAnkfI8J/solid-docs-next?node-id=0%3A1) with [prototypes](https://www.figma.com/proto/33g5ZOPX2aWDg3uAnkfI8J/solid-docs-next?page-id=0%3A1&node-id=11%3A719&viewport=-2320%2C573%2C0.69&scaling=min-zoom&starting-point-node-id=11%3A719&show-proto-sidebar=1) in hope to fix some of the issues. I didn’t changed any of the structure so the changes will not introduce breaking changes (mainly padding and colors fixes). I believe the docs use tailwind so I used their colors to allow a quick implementation.

I think having a beautiful doc will help solid attract more and more people and would love to be part of that. I can start working on a PR to implement these modifications, but everyone can copy the Figma file and make their own modifications !

![solid-docs-next](https://user-images.githubusercontent.com/4331575/184349761-167df968-e402-40a0-aee7-5c737ba18e14.png)

**Comment by Yan-Thomas** [comment]
Loved this, fantastic work @robin4a4!

**Comment by Jutanium** [comment]
Woah!! Thank you so much! We've been leaving design for last, but this is beautiful. Pinging @davedbase for thoughts about whether we should implement this.

**Comment by davedbase** [comment]
This looks great! I think the nav element changes are a huge improvement. Keep up the good work! I'm wondering how the docs will integrate with the current Solid Site at this point. The only two requirements I'd have is introducing the current Solid navigation and footer. After that ensuring that the colours and UI are paired nicely would final step.

Not important for now, but something to think about for sure.

**Comment by Jutanium** [comment]
@davedbase @robin4a4 In terms of implementing the design, we can save the "common nav" stuff for last, when Solid Site an Docs Site are integrated.

@robin4a4 Please let me know how we can encourage you to work on this more! Are you interested in implementing this design?

**Comment by robin4a4** [comment]
@Jutanium I would love to start a PR! With tailwind I think it should be easy to switch colors schemes if it does not integrate well with the solid site later. I am currently on vacation (I did the design between to hikes 🥾) so I can’t start until next week but I don’t think we are in a hurry right ?

**Comment by Jutanium** [comment]
Yup, no rush! Thanks again!

**Comment by Hopelezz** [comment]
@robin4a4 Looks great. Thoughts on light mode?

I was thinking #89BEE7 (The light blue of Solid) for the light background with black text.

I'd also like to add a note on accessibility:
Some people are blue spectrum colorblind and this might cause issues distinguishing between the colors. Any chance on a neutral color scheme?

**Comment by robin4a4** [comment]
@Hopelezz thanks ! I am currently experimenting with different colour scheme for light mode in the tmp page of the Figma file and I will definitively try your idea. For the neutral colour scheme their is one in the tmp folder too !

**Comment by davedbase** [comment]
You might want to look at Solid Site. Colours will likely be defined by that platform. Remember any UI and design decisions will have to mesh with the main website. We cannot have a separate docs looking site from the marketing and info site.

Thanks! :-)

**Comment by Jutanium** [comment]
@robin4a4 Colors aside, the UI updates are super awesome here, and I'd love to work with you to make this happen.

**Comment by robin4a4** [comment]
@Jutanium @davedbase As I started coding, I noticed some new UI element that could benefit from a little redesign so I added them in the Figma (the interactive bookshelf example for instance). I also noticed a future search input so I added it in the Figma model. 
It is very much a work in progress but the basis are here. I also added the True Tone version in the main page. I only swapped the colours schemes so I will need to work a little more on this neutral version to make it look better. 

I am going forward with the blue version and when the neutral version is ready we will only need to change 
`const colorScheme = colors.slate` to `const colorScheme = colors.neutral` in the vite.config.ts. 

Thanks again for your feedbacks !

**Comment by Jutanium** [comment]
@robin4a4 yessss it looks awesome! Yeah, we really need to style that bookshelf

**Comment by robin4a4** [comment]
During my trip back from vacation I added the previous and next links design to the Figma and I also started looking to introduce the nav bar to see how it could be done. I made a blue version and a dark one mostly for fun. Also, I started coding (I have the color scheme and spacing corrections done, as well as the "preference" form). Can I open a PR even if it is not the final code or do you want only PR's that can be reviewed ? There are some things that I might need help to fix, for exemple the fact that the text in the Aside component is treated as a <p> which includes some vertical margin that I wish I could remove. Thanks in advance for your feedbacks !

**Comment by Jutanium** [comment]
@robin4a4 go for it, just label the PR as a draft!

**Comment by robin4a4** [comment]
Hi ! I just pushed a series of commits on the PR that introduce some of the ui element of the Figma. I focused on dark mode for now but I think I made some cool progress. I am still in the process of styling the entire bookshelves but I think the little "interactive example" widgets looks great and help to understand what is a demo or not.

Let me know what you think of it ! I also must say that while navigating the new docs I found the content to be really great and I think it will help a lot in learning Solid.

**Comment by Hopelezz** [comment]
Suggestion: a small border between the sidebar and content?

1 or 2px but doesn't extend the full length

Example:
![Screenshot_20220827-170517_Chrome.jpg](https://user-images.githubusercontent.com/72772558/187049551-bce96178-7522-456c-9185-92cba8ca902f.jpg)

**Comment by Jutanium** [comment]
@robin4a4 This is incredible! I hope to get around to it soon, but personally I'm happy to merge this

**Comment by robin4a4** [comment]
Hi everyone ! I completed my checklist on the PR [#142](https://github.com/solidjs/solid-docs-next/pull/142), there are some things that I think I should have done differently but I didn't have much time this month. Overall I quite like navigating [the preview](https://deploy-preview-142--solid-docs.netlify.app/). Let me know what you think ! It has been a fun project, I learned lot about solid and exploring a new code base.

**Comment by michaelessiet** [comment]
> Hi everyone ! I completed my checklist on the PR [#142](https://github.com/solidjs/solid-docs-next/pull/142), there are some things that I think I should have done differently but I didn't have much time this month. Overall I quite like navigating [the preview](https://deploy-preview-142--solid-docs.netlify.app/). Let me know what you think ! It has been a fun project, I learned lot about solid and exploring a new code base.

Awesome work! It looks great. Can't wait for it to get merged

**Comment by michaelessiet** [comment]
> Suggestion: a small border between the sidebar and content?
> 
> 1 or 2px but doesn't extend the full length
> 
> Example: ![Screenshot_20220827-170517_Chrome.jpg](https://user-images.githubusercontent.com/72772558/187049551-bce96178-7522-456c-9185-92cba8ca902f.jpg)

I'll try this out and see how it looks. After that I think it'll be safe to close this issue
