### ISSUE TITLE
Filename extension does not change when I toggle from JS to TS and vice versa.

### ISSUE THREAD

**Issue by Njong392** [solidjs/solid-docs-next#139]
- A description of the problem

In the new docs, I see that one has the option to check out code snippets in both JS and TS. And as the code snippet changes, some parts of the text like file names and sorts change as well.

But if we check [this page](https://docs.solidjs.com/tutorials/getting-started-with-solid/building-ui-with-components#using-a-component), there is some text that goes thus,
"Then, let's replace the boilerplate in **App.tsx**..."

Now, when I switch between languages, say from JS to TS, the filename in the small nav switches from `App.jsx` to `App.tsx`, and the component name in the text switches from `HelloWorld.jsx` to `HelloWorld.tsx`, but the part which I have marked in bold above, does not change with the switch.

Is this perhaps an error? This could be a little confusing for JS users, even though it was mentioned somewhere before that these little changes don't really matter.

**Comment by Jutanium** [comment]
Thank you, @Njong392! So glad to see you here! Went ahead and fixed.
