### ISSUE TITLE
Bug: getting started files image contains both package-lock.json and pnpm-lock.yaml

### ISSUE THREAD

**Issue by nirtamir2** [solidjs/solid-docs-next#140]
Bug: Getting started tutorial images contains both `package-lock.json` and `pnpm-lock.yaml`
I think it's better to keep only one lock file - in this case `package-lock.json`.
The images in the code are located at:

https://github.com/solidjs/solid-docs-next/blob/main/public/images/tutorial/template-files-js.png

https://github.com/solidjs/solid-docs-next/blob/main/public/images/tutorial/template-files-ts.png

And we can see them when we navigate to
https://docs.solidjs.com/tutorials/getting-started-with-solid/installing-solid#understanding-the-project-structure

![image](https://user-images.githubusercontent.com/16452789/185760229-6903b99a-4dba-4ab5-a1f1-f459473428c0.png)

**Comment by Jutanium** [comment]
These screenshots come from our templates, which we suggest as a starting point in the tutorial.

Feel free to submit an issue [there](https://github.com/solidjs/templates/), though I do think this is desirable for the templates.

Are you suggesting that we tell the reader to remove one? I don't really want to interject with that in this "up and running" tutorial, but if you have an argument for doing so, I'm happy to hear it.

**Comment by Jutanium** [comment]
I believe this is a Stackblitz thing - will update the screenshots when I get a chance
