### ISSUE TITLE
Content: Describe how createResource can take more than one signal

### ISSUE THREAD

**Issue by EkaanshArora** [solidjs/solid-docs-next#156]
Hi everyone!

I really like the new docs, I'm just beginning with Solid and going through the tutorial was finding a way to pass in more than one signal to the `createResource` primitive and was unable to find it mentioned in the docs. I found an answer [here](https://stackoverflow.com/questions/73086335/solidjs-is-there-a-way-to-pass-in-an-object-to-the-first-param-of-createresour/74576619#74576619) but it wasn't very easy to understand.

Do you think it's valuable to add how to do this in the docs? Maybe not in the initial tutorial but in the reference it can be nice to describe with an example how this can work.

If this makes sense, I'm happy to draft an example. Hope this helps someone, sorry if this isn't a priority for the docs.

Here's the code I came up with, I'm not sure if it's correct:

I defined two signals:
```ts
  const [state1, setState1] = createSignal("");
  const [state2, setState2] = createSignal("");
```
Created a function that derives the state from those signals:
```ts
  const derivedState = () => {
    console.log('func called')
    return {value1: state1(), value2: state2()}
  }
```
Used it with createResource:
```ts
  const [data] = createResource(derivedState, fetcherFunction);
```
This is what my fetch function signature looked like:
```ts
async function fetcherFunction(derivedState: {
  value1: string;
  value2: string;
}) {
  ...
```

**Comment by michaelessiet** [comment]
Thanks for this, this is very helpful info. We'll make sure to add it to the new docs

**Comment by EkaanshArora** [comment]
Awesome, let me know if there’s something I can help with!

**Comment by michaelessiet** [comment]
Quick update on this. I was playing around with this and there's no need for you to have a separate derived state function, if you would like to keep the derived state somewhere I would suggest making use of createMemo since it will at least remain reactive throughout the lifecycle of the application. 

```jsx
function MyComponent() {
	const [state1, setState1] = createSignal(0);
	const [state2, setState2] = createSignal(1);
	const derivedState = createMemo(()=>({value1:state1, value2:state2}));

	const myResource = createResource(derivedState, fetcherFunction);
	
	...
}
```
