### ISSUE TITLE
File names in new api reference markdown files are invalid

### ISSUE THREAD

**Issue by NathanPip** [solidjs/solid-docs-next#182]
Windows doesn't like the file names for the api reference, i.e. content/references/api-references/special-jsx-attributes/attr:_.mdx. 
OS won't let git make the directories and git throws an "invalid path" error when trying to pull from origin or checkout the main branch.

I believe it's the colon ":" in the filenames that's causing the issue.

**Comment by michaelessiet** [comment]
Thank you for pointing this out. I'll remove special characters from the file names
