### ISSUE TITLE
CloudFlare "Auto Minify" breaks SolidJS

### ISSUE THREAD

**Issue by Moudoux** [solidjs/solid-docs-next#185]
### Describe the bug

I'm not sure if this is just solidjs itself, or related to solid-start as well, but I'm creating the bug here in any case. I am using solid-start with SSR enabled for an app, running behind CloudFlare. Enabling the "Auto Minify" options, in the Speed -> Optimizations tab, causes solidjs reactivity to break. Since this is not related to some specific code, I don't have a repo or page to provide, since CloudFlare is needed to test and verify the issue.

The console logs the following error when auto minify is enabled:

![Screenshot 2023-01-14 141413](https://user-images.githubusercontent.com/14980525/212473343-92ecd090-fe3d-4d0e-94a7-b66d4ff79b70.png)

There are no issues at all if I disable the auto minify option.

### Your Example Website or App

not applicable, any reactive app will produce the behavior

### Steps to Reproduce the Bug or Issue

1. Create or use a solidjs app with some reactivity features
2. Deploy it and use CloudFlare in front of it
3. Enable all "Auto minify" options in Speed -> Optimization
4. Go to the deployed app and reactivity will be broken

### Expected behavior

I expect the solidjs app to work without issues even with these settings enabled.

### Platform

- OS: Tested on Windows and Linux
- Browser: Brave
- Version: v1.47.171

### Additional context

I'm not sure if it's possible to solve this issue, but in that case there should be some sort of documentation of the issue, so other users can prevent this from happening.

**Comment by michaelessiet** [comment]
I'll add this as a footnote to the deploying to cloudflare guide

**Comment by michaelessiet** [comment]
<img width="893" alt="Screenshot 2023-01-20 at 02 05 12" src="https://user-images.githubusercontent.com/23281128/213596009-54edb74d-ed40-40b7-9ead-9e1b93149016.png">
Not sure if this is enough information. I can't really test is as I don't have a site to test it with. If more information needs to be added to this please let me know

**Comment by ryansolid** [comment]
Seems fine. Thanks Michael.
