### ISSUE TITLE
https://docs.solidjs.com/ right sidebar is broken

### ISSUE THREAD

**Issue by shinebayar-g** [solidjs/solid-docs-next#186]
Documentation main page's https://docs.solidjs.com/ right sidebar is broken. Pls see attached gif.

![2023-01-14-22-48-36](https://user-images.githubusercontent.com/3091558/212527286-b884632b-6416-4e7e-9350-884b6a0e4fdb.gif)

**Comment by michaelessiet** [comment]
This will be fixed this weekend in the upcoming merge
