### ISSUE TITLE
Add Solid Playground to the new docs

### ISSUE THREAD

**Issue by michaelessiet** [solidjs/solid-docs-next#190]
Here's the link to the official solid playground repo https://github.com/solidjs/solid-playground

The key areas to add the Solid Playground in the new dos would be the api reference sections. For instance createRenderEffect, createDeferred, useTransition and createResource just to name a few, would do well to have interactive examples

**Comment by michaelessiet** [comment]
Current progress @atk started a new playground project using codemirror [here is the repo](https://github.com/solidjs-community/solid-playground-editor-cm). We will be developing this from scratch and be using this instead of the old solid playground used in the old docs.

So far we only have the editor with linting and code completion. I'm currently working on a separate repo of a full blown playground with rendering, console and editor

**Comment by atk** [comment]
The old playground had some issues that stopped it from working in solid-start and was also somewhat monolithic. We wanted to keep the parts making up the playground as modular and replaceable as possible, in order to help future development, so we decided on a rewrite.
