### ISSUE TITLE
Inconsistent use of "Solid" vs "Solid.js / SolidJS / etc."

### ISSUE THREAD

**Issue by Brian-Pob** [solidjs/solid-docs-next#235]
The WRITING.md guide says to use "Solid" to refer to the framework instead of SolidJS when working within the context of the docs.
https://github.com/solidjs/solid-docs-next/blob/8cf21bf3de3e453972fdf376f0f672af25546c2e/WRITING.md?plain=1#L228

Several pages do not follow this rule. Here are some that I have found:

- https://github.com/solidjs/solid-docs-next/blob/8cf21bf3de3e453972fdf376f0f672af25546c2e/content/references/index.mdx - "SolidJS"
- https://github.com/solidjs/solid-docs-next/blob/8cf21bf3de3e453972fdf376f0f672af25546c2e/content/guides/foundations/why-solid.mdx - "Solid.js"
- https://github.com/solidjs/solid-docs-next/blob/8cf21bf3de3e453972fdf376f0f672af25546c2e/content/guides/foundations/thinking-solid.mdx - "Solid"

Could this issue be assigned to me? I plan to make a PR before Sunday, Mar. 19 fixing whatever inconsistencies I find.

**Comment by michaelessiet** [comment]
Thank you for pointing this out. Feel free to add this to your PR tomorrow

**Comment by Brian-Pob** [comment]
Resolved with #230
