### ISSUE TITLE
Formatting errors

### ISSUE THREAD

**Issue by Brian-Pob** [solidjs/solid-docs-next#237]
1. [`Guides/Foundations/Thinking Solid`](https://docs.solidjs.com/guides/foundations/thinking-solid) uses numbers in each subheading. This causes numbers to appear twice in the page summary

<img width="331" alt="CleanShot 2023-03-19 at 13 34 29" src="https://user-images.githubusercontent.com/29676413/226195610-e21a99f7-a8b7-4c2a-bed3-e08b0b9c5ab1.png">

2. [`Guides/Tutorials/Getting Started with Solid/Control Flow`](https://docs.solidjs.com/guides/tutorials/getting-started-with-solid/control-flow) `<` and `>` not rendering properly.

<img width="321" alt="CleanShot 2023-03-19 at 13 35 43" src="https://user-images.githubusercontent.com/29676413/226195658-5c28e3b2-5b76-45bc-887f-8339bab30bc1.png">

**Comment by michaelessiet** [comment]
Thanks for spotting this. I'll fix this within the week

**Comment by Brian-Pob** [comment]
I'd actually like to resolve these issues if it's alright.
