### ISSUE TITLE
TailwindCSS init command error

### ISSUE THREAD

**Issue by Saga-sanga** [solidjs/solid-docs-next#243]
-  TailwindCSS init command `npx tailwindcss init --poll` creates a new file `--poll` and not the tailwind config file. 
- https://docs.solidjs.com/guides/how-to-guides/styling-in-solid/tailwind-css
- This command fails to create the tailwind config file with the correct file name. This affects anyone who wishes to refer to the docs as a guide to install Tailwind to their project.
- Update command to the correct command.

**Comment by michaelessiet** [comment]
Thanks, will get it updated in next merge

**Comment by Saga-sanga** [comment]
I can submit a PR for it too.
