### ISSUE TITLE
[SSR] Wrong documentation (+ possible bug)

### ISSUE THREAD

**Issue by KevinBLT** [solidjs/solid-docs-next#261]
### Describe the bug

I was playing around with `renderToStream` and came along this page: https://docs.solidjs.com/references/concepts/ssr/streaming

When using the exact example at the bottom (without `<Suspense>`), it will (as I already wondered before I tried) throw this error:
```
return ssr(_tmpl$, ssrHydrationKey(), escape(data().title));
                                                     ^
TypeError: Cannot read properties of undefined (reading 'title')
```

Which was expected by me, but this is in this documentation.

Another thing, which I didn't know: The `renderToStream()` function will not work, if I only have a resource without `<Suspense>`  around it. Then actually nothing will ever come (at least without hydration). Is that correct behavior?

This will not work:  
```jsx
import { HydrationScript } from "solid-js/web";
import { createResource } from 'solid-js';

async function fu() {
  console.log('Yes this will call');

  await new Promise(r => setTimeout(r, 4000));
  
  return 'never seen';
}

export default () => {

  const [data] = createResource(fu);

  return  <html lang="en">
    <head>
      <title>🔥 Solid SSR 🔥</title>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <HydrationScript />
    </head>
    <body>
      <span>{ data() }</span>   
    </body>
  </html>
}
```

```jsx
import { renderToStream } from 'solid-js/web';
import App from './app';

export const render = () => renderToStream(() => <App/>, {
  onCompleteAll: () => console.log('ALL', new Date()),
  onCompleteShell: () => console.log('SHELL', new Date())
});
```
Although the fetcher is called, `data()` is never resolved and won't show. If it's in a `<Suspense>` it works, but I would say this should not be a must?

### Your Example Website or App

Code above

### Steps to Reproduce the Bug or Issue

Create SSR with the code above.

### Expected behavior

Stream the value of resolved promise for resource `data()`

### Platform

- OS: macOS
- Chrome
- node --version v20.1.0

**Comment by michaelessiet** [comment]
I haven't used this much but I'll try the example you posted

**Comment by michaelessiet** [comment]
@KevinBLT please can you share a reproduction of this?

**Comment by KevinBLT** [comment]
> @KevinBLT please can you share a reproduction of this?

Do you mean like this?
[ok_test.zip](https://github.com/solidjs/solid-docs-next/files/12248772/ok_test.zip)

`npm i && vite build --ssr test.jsx && node dist/test.js ``

It wIll work with `<Suspense>` around it. Aa Ryan said, the documentation does not match reality. Also it is just combining jsx with express. I think for many beginners will not work out of the box here.

**Comment by LadyBluenotes** [comment]
Consolidated this into #473
