### ISSUE TITLE
Broken and missing links on Reactivity page

### ISSUE THREAD

**Issue by GusSL** [solidjs/solid-docs-next#263]
In the [Reactivity page](https://github.com/solidjs/solid-docs-next/blob/main/content/references/concepts/reactivity/index.mdx), exist the following problems:

https://github.com/solidjs/solid-docs-next/blob/54f9f61caf133ed960a3edd0eefe729c8300ec0c/content/references/concepts/reactivity/index.mdx#L212

The missing link should point to the [`on` utility](https://github.com/solidjs/solid-docs-next/blob/main/content/references/api-reference/reactive-utilities/on.mdx).

Both

https://github.com/solidjs/solid-docs-next/blob/54f9f61caf133ed960a3edd0eefe729c8300ec0c/content/references/concepts/reactivity/index.mdx#L214

and

https://github.com/solidjs/solid-docs-next/blob/54f9f61caf133ed960a3edd0eefe729c8300ec0c/content/references/concepts/reactivity/index.mdx#L222

should point to `./tracking` instead of `../tracking`. Maybe consider removing 222, since it's already integrated in the docs.

**Comment by LadyBluenotes** [comment]
Closing stale issues - if this is still an issue with the new docs when they're released, please file another issue!
