### ISSUE TITLE
Writing Guide Revisions

### ISSUE THREAD

**Issue by LadyBluenotes** [solidjs/solid-docs-next#268]
<h2>The Problem</h2>

Currently, our writing guide is not bad. However, it needs to be reworked so that it will be consistent with our new documentation practices. 

<h2>Scope</h2>

Our writing guide needs to be completed for the new documentation. This guide will define our voice and tone, visual style, etc. The intention is for contributors to have a place to begin when they are looking to assist with the documentation. 

This writing guide will also serve as a framework for maintainers / editors to reference while editing contributions.

**Comment by jccpalmer** [comment]
I have already started working on the structure and I have written a first draft of the introduction.

**Comment by LadyBluenotes** [comment]
closed with #270
