### ISSUE TITLE
[docs-rewrite] Contribution Guide

### ISSUE THREAD

**Issue by LadyBluenotes** [solidjs/solid-docs-next#279]
* Explain current issue labels
* Elaborate on large PR's.
     * When to reach out.
     * What warrants a large PR.
* Note for netlify link - only going to happen when merging to `main`.
* Note SolidStart v0.1.0-alpha
     * Write the requirements of how to use (eg. node version, etc).
* Update Folder Structure section
     * folder names
     * pages
     * broken link management for `Getting Started with Solid folder`
* How to add new content pages

Overall Contribution Guide could use a better structure. Additionally, information could be better laid out for readers.

**Comment by CBID2** [comment]
I think it would be beneficial to have a suggestion on reviewing PRs. It would be an awesome way for people who are new to contributing to Solid JS can have a way to start.

**Comment by darrenbarklie** [comment]
Hey @LadyBluenotes, I'm keen to support this new, new docs effort! I'm a practiced React dev, but relatively new to Solid and open source. As @CBID2 suggested, I'd appreciate defining/understanding the intended workflow for collaboration and PR submissions.

**Comment by LadyBluenotes** [comment]
Hello to both @CBID2 and @darrenbarklie.

Everything with the docs effort is still quite new and can evolve. I'm working towards refining the process of how roles will be defined. I appreciate both of your interests in working with Solidn

As far as reviewing PRs go, we've got an existing plan for this for the rewrite. Unfortunately an existing understanding of knowledge is required for this. 

We will have "help-wanted" labels on parts of the project that we need help on, so if you'd like to assist in any way watching that would be a great idea 🙂

I will add things we need help with in the #docs channel of the discord! So that's another great place to follow if you want to get involved 😉

**Comment by CBID2** [comment]
> Hello to both @CBID2 and @darrenbarklie.
> 
> Everything with the docs effort is still quite new and can evolve. I'm working towards refining the process of how roles will be defined. I appreciate both of your interests in working with Solidn
> 
> As far as reviewing PRs go, we've got an existing plan for this for the rewrite. Unfortunately an existing understanding of knowledge is required for this. 
> 
> We will have "help-wanted" labels on parts of the project that we need help on, so if you'd like to assist in any way watching that would be a great idea 🙂
> 
> I will add things we need help with in the #docs channel of the discord! So that's another great place to follow if you want to get involved 😉

Great! :)

**Comment by LadyBluenotes** [comment]
Closed with #290
