### ISSUE TITLE
Mention non-JSX usage of Solid

### ISSUE THREAD

**Issue by crutchcorn** [solidjs/solid-docs-next#28]
While I understand the focus of JSX in our docs currently, one of the things that made Solid stand out to me initially (and helped distinguish it from compiler-based solutions like Svelte) was its ability to run its templating at runtime with the usage of [`@solid/html`](https://www.solidjs.com/examples/simpletodos).

Would it be worthwhile to include an aside in our `What is JSX` section that indicates that JSX is not the only choice for Solid - simply the default pick?

**Comment by nas5w** [comment]
Sure! I think we have two options here: just mention it in passing or put a couple sentences in an "advanced" aside. One thing we're going for in the Getting Started tutorial is simplicity so we don't confuse newcomers. I'd prefer it not come off as a choice of JSX or something else that newcomers need to make, but rather an "oh by the way you can opt into this other way of rendering if you really want."

**Comment by crutchcorn** [comment]
I definitely think an "advanced" aside is the way to go here. I'll throw up a PR to add this - I have an idea of what and where to say that.
