### ISSUE TITLE
[feature] Install Tabs

### ISSUE THREAD

**Issue by LadyBluenotes** [solidjs/solid-docs-next#284]
I think it could be worthwhile introducing a tab component that has `yarn`, `npm` and `pnpm` vs requiring us to write it out.

Would love to you know your thoughts @michaelessiet & @davedbase.

The idea is similar to what Astro currently has:

<img width="785" alt="A screenshot of astro's npm, yarn and pnpm tabs" src="https://github.com/solidjs/solid-docs-next/assets/98355961/01032b3c-89b3-4495-952d-2266bd6b44f2">

**Comment by davedbase** [comment]
Love it. Kobalte has a good tabs component

**Comment by michaelessiet** [comment]
Great idea, I'll make it happen

**Comment by LadyBluenotes** [comment]
Thanks, @michaelessiet!

**Comment by LadyBluenotes** [comment]
closed with #318
