### ISSUE TITLE
Trying to navigate while offline breaks all interactive elements

### ISSUE THREAD

**Issue by FeldrinH** [solidjs/solid-docs-next#288]
The following sequence of actions breaks all interactive/clickable elements on the page until the next reload:
1. Load the page
2. Disable internet connection
4. Click any link that causes navigation

After these steps clicking any link, dropdown menu or other interactive element does nothing, even if your internet connection is restored. No errors are shown to the end user (there are a some errors in the devtools console).

PS: This feels like something that should be handled at the framework level i.e. in SolidStart or the Solid Router, but I don't know enough about the internals of those projects to create an actionable issue there.

https://github.com/solidjs/solid-docs-next/assets/5256211/91bf3221-fb33-483d-8b53-0ffd1d165bed

**Comment by FeldrinH** [comment]
What was the resolution here? Is this fixed? If it is then the update doesn't seem to have reached the public docs.solidjs.com page yet.

**Comment by LadyBluenotes** [comment]
There will be changes to the site infrastructure with the docs update - the current site is using a version of solid start that is outdated. When the new site is up, if you notice this issue persists, please open another issue!
