### ISSUE TITLE
Pointless use of `createMemo` when deriving resource's source value

### ISSUE THREAD

**Issue by thetarnav** [solidjs/solid-docs-next#300]
[This sections is the docs](https://docs.solidjs.com/guides/foundations/solid-primitives#createresource) seems off:

> If you want to use multiple signal values within a single resource, you can do so by creating a derived state with the `createMemo` primitive. You may be wondering why I'm using the `createMemo` primitive instead of just creating a standard derived state. That's because `createMemo` will aid in keeping your derived state reactive, whereas if you create a normal derived state, the derived state will not be updated if the state value changes. Here's how it might look in action.
> ```ts
> import { createResource, createMemo } from "solid-js";
> 
> // the fetcher function changed to accept an object
> async function fetcherFunc(info: { id: number; name: string }) {
>   const response = await fetch(
>     `https://jsonplaceholder.typicode.com/users/${info.id}/posts?name=${info.name}`
>   );
>   return await response.json();
> }
> 
> const [id, setId] = createSignal<number>(1);
> const [name, setName] = createSignal<string>("");
> 
> // the derived state made using createMemo
> const derivedState = createMemo(() => ({ id: id(), name: name() }));
> const [posts] = createResource(derivedState, fetcherFunc);
> ```

1. The added `?name=___` to url doesn't seem to do anything if I tried using it
Something like this might be better: [`https://jsonplaceholder.typicode.com/users/${info.id}/posts?id=${info.postId}`](https://jsonplaceholder.typicode.com/users/1/posts?id=3)

2. The resource will keep working even if we don't use a memo
If you just replace `createResource(derivedState, fetcherFunc)` with `createResource(() => ({ id: id(), name: name() }), fetcherFunc)` you'll have the same result. The resoure will refetch on each signal change.

I'm not making a PR because removing the memo will make the section pointless, so it would need to be rewritten.
What was the actual goal behind this section?
I cannot think of a good example where using a memo specifically to be used with a resource would be the recommended way. Memos are good for "if you don't want to rerun this on each read" situations, which are not resource-specific.

I guess the section could just be left as "if you want to use multiple values as the source, you can just pass any function that reads from them".

**Comment by michaelessiet** [comment]
You're right about the last part about using functions for multiple variables. I'll keep this in mind while @LadyBluenotes and I rewrite these sections. 

I chose to use createMemo because of the tracked scope linting warning. I'll take a look at this again though
