### ISSUE TITLE
Installation and setup page removal

### ISSUE THREAD

**Issue by michaelessiet** [solidjs/solid-docs-next#308]
In the [content-rewrite branch](https://github.com/solidjs/solid-docs-next/tree/content-rewrite) the Installation and setup page contains information unsuitable for the page title. The content would be better contained in different pages such as the Typescript for Solid page for the topic on "Migrating from Javascript to Typescript" and the Quick Setup page for the "Environment variables" topic. This way relative information is better housed and navigation made less confusing.

**Comment by LadyBluenotes** [comment]
removed with #309
