### ISSUE TITLE
windicss is sunsetting

### ISSUE THREAD

**Issue by samualtnorman** [solidjs/solid-docs-next#319]
it should either be removed from the docs (https://docs.solidjs.com/guides/how-to-guides/styling-in-solid/windicss) or a similar message should be displayed as on https://windicss.org/ near the top
> Windi CSS is Sunsetting
We recommend new projects to consider alternatives. Click for more information.

**Comment by michaelessiet** [comment]
Thanks for mentioning this. I'll make sure to add it to the page and bring it up to the other docs members to decide whether we want it to stay in the docs or not
