### ISSUE TITLE
React-ism in routing guide?

### ISSUE THREAD

**Issue by eteeselink** [solidjs/solid-docs-next#320]
I'm still learning SolidJS. This here is an issue and not a PR because I'm not confident I really did find a bug in the docs.

My key gotcha when learning SolidJS was that all logic that should change when data changes, needs to be directly inside the JSX and not just before, like you do with React. This is well documented, so I was pretty surprised when seeing the following code in the [Solid Router guide](https://docs.solidjs.com/guides/how-to-guides/routing-in-solid/solid-router):

```tsx
  return (
    <div>
      {data.loading ? ( // 👈 Use the loading property to show a loading indicator
        <p>Loading...</p>
      ) : (
        <div>
          <p>Name: {data().name}</p> {/* 👈 Access the data returned from the fetchUser function */}
          <p>Email: {data().email}</p>
          <p>Phone: {data().phone}</p>
        </div>
      )}
    </div>
  );
```

https://github.com/solidjs/solid-docs-next/blob/main/content/guides/how-to-guides/routing-in-solid/solid-router.mdx#L336

This `data.loading ? x : y` style is the kind of code I mistakenly wrote a bunch of times when un-learning React, is this wrong in the docs? Shouldn't it be a bunch of `<Show>` invocations instead?

**Comment by michaelessiet** [comment]
Yes, it should be <Show> or <Suspense>. This is currently being corrected along with some other pages
