### ISSUE TITLE
Broken YouTube link on Guides: Getting Started page

### ISSUE THREAD

**Issue by ivangermanov** [solidjs/solid-docs-next#328]
**Description**
There is a broken link to a YouTube video titled **Solid reactivity in 10 minutes**. The video seems to have been deleted.

**Reproduce the issue**
1. Open the [Guides: Getting Started](https://www.solidjs.com/guides/getting-started#see-solid) page
2. Click on the **Solid reactivity in 10 minutes** link to the YouTube video (at the time of writing, [this is the current YouTube link](https://www.youtube.com/watch?v=J70HXl1KhWE))
3. YouTube is opened, you get "This video isn't available anymore":
<img width="395" alt="This video isn't available anymore" src="https://github.com/solidjs/solid-docs-next/assets/42522864/e5633274-d4c0-4fb4-b1d4-b14413a5dc00">

**Why is this a problem**
There shouldn't be a broken link, especially on the first **Getting started** page.

**Proposed fix**
Either fix/reupload the video on YouTube and update the link or remove the link altogether.

**Comment by ivangermanov** [comment]
Connected with this issue: https://github.com/solidjs/solid-docs/issues/260

**Comment by michaelessiet** [comment]
Thanks you for catching this. This has been noted and addressed

**Comment by krishna-santosh** [comment]
@michaelessiet it still seems to be broken :/

**Comment by michaelessiet** [comment]
Sorry, I meant that this is being addressed by the new docs that we still have in development. However, I will create a PR to update the current doc site
