### ISSUE TITLE
What's the current plan with i18n?

### ISSUE THREAD

**Issue by timotius02** [solidjs/solid-docs-next#34]
I wanted to contribute translations to the old docs but held off when I saw plans for a new docs site, since I wasn't sure about what would happen to the old docs.

However, in the new docs, I don't see any references to translation efforts/UI controls that allow for changing language. 

Is the new docs still too early to consider i18n? And should people who want to contribute translations focus their efforts on the old site instead?

**Comment by nas5w** [comment]
This is a great question. My opinion is this is far too early to translate the new docs since they're going to change _a lot_ over the coming months. They will absolutely need translation eventually though, we're just not there yet.

@Jutanium what are your thoughts?

**Comment by Jutanium** [comment]
Exactly as @nas5w said - we absolutely will need translators but it's too early. 
As for what to do now: the [Feature Tutorial](https://www.solidjs.com/tutorial/introduction_basics) and [API Docs](https://www.solidjs.com/docs/latest/api) will remain largely the same from the old site to the new site, so these are perfect to focus on in the meantime :)
