### ISSUE TITLE
[content-rewrite] Stores

### ISSUE THREAD

**Issue by LadyBluenotes** [solidjs/solid-docs-next#352]
Explain what stores are and how they are used

**Comment by q1b** [comment]
@LadyBluenotes I have used Store for a Big Project, Maybe that would be helpful for writing docs about them.

Here, are the use cases I find during use of createStore
- It's reactive nature, differs from the createSignal which provides more, flexibility for large complex objects
- It's can be used as global state for the application
- We can create Wrapper around it to automatically, make it sync with localStorage in web browser! ( example )
- It's performant in comparison to other framework solutions! FAQs How it differs from **createSignal**
