### ISSUE TITLE
Copying code omits blank lines

### ISSUE THREAD

**Issue by sh-cho** [solidjs/solid-docs-next#356]
```tsx
import { HelloWorld } from "./HelloWorld";

function App() {
  return (
    <div>
      <h1>Welcome</h1>
      <HelloWorld />
    </div>
  );
}

export default App;
```

For example, in https://docs.solidjs.com/guides/tutorials/getting-started-with-solid/building-ui-with-components, if I'm trying to copy this with button,

```tsx
import { HelloWorld } from "./HelloWorld";
function App() {
  return (
    <div>
      <h1>Welcome</h1>
      <HelloWorld />
    </div>
  );
}
export default App;
```
Result is like this.

It's not a big deal, but it's somewhat annoying.

**Comment by LadyBluenotes** [comment]
This should hopefully be addressed when finish the site infra we're doing with PR #382 :) If you notice this still happening once the new site is updated, please let us know!
