### ISSUE TITLE
[usability] Provide links between https://www.solidjs.com/ and https://docs.solidjs.com/

### ISSUE THREAD

**Issue by aryzing** [solidjs/solid-docs-next#358]
The new docs site is looking great! While browsing the docs site though, there doesn't seem to be a way to navigate to the main site? At times its useful to jump to the main site to review a section of the tutorial or open a new playground. 

Not having a link to the main site makes the two sites feel disconnected. Not sure if this is by design or if eventually they'll converge into one? In any case, being able to jump b/w the two would quite helpful as users learn about solid.

**Comment by LadyBluenotes** [comment]
I really appreciate you bringing this up! I've added some links between the sites with the new docs.

It won't be immediately shown with the current site, but when we release the new docs you should notice the changes. Thank you!
