### ISSUE TITLE
Clarification of SSG limitations

### ISSUE THREAD

**Issue by PeterDraex** [solidjs/solid-docs-next#364]
Hello,

I am a new user reading docs for the first time and I wanted to ask for clarifications of section `Static Site Generation - Limitations`. It says:

> The main limitation of SSG in general is that it is completely static, meaning that there will be **little** to no user interactions and site data can only be updated if the site is completely rebuilt. This is why it is advised to use static site generation only in cases where a user will not be interacting with the site or if user interactions will be **minimal**. 

Would it be possible to clarify what is the "little"/"minimal" user interaction that is possible on a SSG site? Given that the next paragraph says that the generated sites "they do not run any javascript", I am assuming that only CSS-based interactivity is possible?

Is that correct? I think it would be good to rewrite that part of the docs. I'll be happy to give it a shot, if somebody explains to me how it works. Thanks!

**Comment by LadyBluenotes** [comment]
@modderme123 is it possible you could help answer this question?

**Comment by LadyBluenotes** [comment]
Consolidated this into #473
