### ISSUE TITLE
Ref section doesn't explain when to use a regular variable vs a signal to store ref

### ISSUE THREAD

**Issue by JasonHassold** [solidjs/solid-docs-next#368]
The current Ref section shows only an example setting the ref to a normal variable. But there are instances where this will not work correctly and a signal should be used instead. If the element with the ref element is not immediately created or is conditionally rendered in and out then code using the ref will not be triggered to rerun.

![image](https://github.com/solidjs/solid-docs-next/assets/25469167/583a33b1-0ee6-4561-b196-bdd93d310ec4)

![image](https://github.com/solidjs/solid-docs-next/assets/25469167/350214bf-cba8-437d-8ef7-befe2bd59503)

![image](https://github.com/solidjs/solid-docs-next/assets/25469167/52559d87-b61a-4c1e-a474-e9df9b28f625)

**Comment by LadyBluenotes** [comment]
Addressed with #371
