### ISSUE TITLE
Blank page in doc

### ISSUE THREAD

**Issue by AesthetiCoder** [solidjs/solid-docs-next#369]
Solid best practices page is empty.

this [page](https://docs.solidjs.com/guides/how-to-guides/get-ready-for-solid/solid-best-practices) is empty i see this pull request but it is not approved #241

also, all the accessibility pages are empty, 

- 1. [Accessibility in Solid](https://docs.solidjs.com/guides/how-to-guides/accessibility-in-solid)
- 2. [Accesibility best practices](https://docs.solidjs.com/guides/how-to-guides/accessibility-in-solid/best-practices)
- 3. [Solid Aria](https://docs.solidjs.com/guides/how-to-guides/accessibility-in-solid/solid-aria)

Motion one is empty

- 1. [MotionOne for Solid](https://docs.solidjs.com/guides/how-to-guides/animations-in-solid/motionone-for-solid)

In testing, uvu is empty

- 1. [Uvu](https://docs.solidjs.com/guides/how-to-guides/testing-in-solid/uvu)

Comparison have also some empty pages

- 1. [Preact](https://docs.solidjs.com/guides/how-to-guides/comparison/preact)
- 2. [Svelte](https://docs.solidjs.com/guides/how-to-guides/comparison/svelte)
- 3. [Angular](https://docs.solidjs.com/guides/how-to-guides/comparison/angular)
- 4. [Qwik](https://docs.solidjs.com/guides/how-to-guides/comparison/qwik)
- 5. [Marco](https://docs.solidjs.com/guides/how-to-guides/comparison/marko)

Frequently Encountered Errors (FEE) is empty

- 1. [Frequently Encountered Errors (FEE)](https://docs.solidjs.com/guides/troubleshooting-and-faq/frequently-encountered-errors)

**Comment by LadyBluenotes** [comment]
With the new Docs we are addressing these pages being empty - thank you for pointing them out!
