### ISSUE TITLE
Arabic Translation 

### ISSUE THREAD

**Issue by mahmood601** [solidjs/solid-docs-next#378]
Hi 👋
I would to translate the docs.
I have looked for translation guideline section but I haven't find it 😐
How can  i start, please 🥺

**Comment by LadyBluenotes** [comment]
Hello @mahmood601 !

we're not at a place where we're ready for the translations of the docs but I will let you know when we are 🙂

**Comment by LadyBluenotes** [comment]
Will be addressed in #441
