### ISSUE TITLE
Reference to <Routes> element in "Solid Router" guide that doesn't exist in exports

### ISSUE THREAD

**Issue by mikeaustin** [solidjs/solid-docs-next#385]
### Describe the bug

In https://docs.solidjs.com/guides/how-to-guides/routing-in-solid/solid-router, it says to import and use `Routes`, but that export does not exists in @solidjs/router. I assume the API has changed since the example works without that element.

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

Go to https://docs.solidjs.com/guides/how-to-guides/routing-in-solid/solid-router and use the second code example that uses `Routes`:

```
import { Router, Route, Routes } from "@solidjs/router";

<Router>
  <Routes>
    <Route path="/" component={App} /> {/* 👈 Define the home page route */}
  </Routes>
</Router>
```

### Expected behavior

Expected example to work, but needed to remove any import or use of `Routes` to get it working. Does the guide need to be updated?

### Screenshots or Videos

N/A

### Platform

- OS: macOS 13.6.1
- solid-js: 1.8.7
- @solidjs/router: 0.10.1

**Comment by sysmat** [comment]
open source have 50 cents, one is good docs, but like angular they have migration schematics/scripts
