### ISSUE TITLE
Formatting Error - Refs Page

### ISSUE THREAD

**Issue by ThatTimTaylor** [solidjs/solid-docs-next#387]
The last two paragraphs of the [Signals as Refs](https://deploy-preview-360--solid-docs.netlify.app/concepts/refs#signals-as-refs
) subsection on the Refs page are formatted incorrectly. The second last paragraph isn't completed and the last paragraph partially repeats the former paragraphs' content.

**Comment by LadyBluenotes** [comment]
updated this as well in the most recent commit for `content-rewrite`
