### ISSUE TITLE
Formatting Error - Stores Page

### ISSUE THREAD

**Issue by ThatTimTaylor** [solidjs/solid-docs-next#388]
There is a formatting mistake under the [Modifying Store Values](https://deploy-preview-360--solid-docs.netlify.app/concepts/stores#modifying-store-values) subsection of the Stores page where several words are repeated unnecessarily.

"For example, if **you wanted to you wanted to** update..."

**Comment by LadyBluenotes** [comment]
just pushed updates for this, thank you!
