### ISSUE TITLE
Deployment Options Page - Summary not showing

### ISSUE THREAD

**Issue by ThatTimTaylor** [solidjs/solid-docs-next#389]
The summary section on the [Deployment Options](https://deploy-preview-360--solid-docs.netlify.app/guides/deploying-your-app) page is not showing. Confirmed to not be showing in Brave Browser, Chromium, and Firefox.

![deploy-summary-not-showing](https://github.com/solidjs/solid-docs-next/assets/143667334/1ed3fd18-bde5-4e8d-9a59-6cfa26d23cc8)

**Comment by ThatTimTaylor** [comment]
On paying closer attention, I noticed several other pages weren't displaying the summary section either. They were as follows:

- [Intro To Reactivity](https://deploy-preview-360--solid-docs.netlify.app/concepts/intro-to-reactivity)
- [Class & Style Bindings](https://deploy-preview-360--solid-docs.netlify.app/concepts/components/class-style)
- [Memos](https://deploy-preview-360--solid-docs.netlify.app/concepts/derived-values/memos)
- [Stores](https://deploy-preview-360--solid-docs.netlify.app/concepts/stores)
- [Routing & Navigation](https://deploy-preview-360--solid-docs.netlify.app/guides/routing-and-navigation)

**Comment by LadyBluenotes** [comment]
Fixed this with the infra update! #382
