### ISSUE TITLE
Typos on data fetching tutorial

### ISSUE THREAD

**Issue by 20jasper** [solidjs/solid-docs-next#405]
There are a few typos in the data fetching tutorial on [the `/guides/fetching-data` route](https://deploy-preview-360--solid-docs.netlify.app/guides/fetching-data).

![Solid JS documentation](https://github.com/solidjs/solid-docs-next/assets/78604367/28a10fab-3c4b-44a3-a65f-fe1f4e6e0bcb)

> The signal returned from the createResource provides the properties that help can assist with conditional rendering based on the current reactive state:
> 
>state: The current status of the opertaion (unresolved, pendign, ready, refreshing, or errored).
>

**Comment by LadyBluenotes** [comment]
Thank you for helping out!
