### ISSUE TITLE
[feat] Add search feature to docs

### ISSUE THREAD

**Issue by elliotwaite** [solidjs/solid-docs-next#407]
It would be nice to be able to search the docs. Maybe something like the search feature that's available on the [Solid Start docs site](https://start.solidjs.com/) could be added.

**Comment by LadyBluenotes** [comment]
I believe @atilafassina and @danieljcafonso are working on this!

**Comment by atilafassina** [comment]
> I believe @atilafassina and @danieljcafonso are working on this!

After talking to @micheleriva, @oramasearch has generously offered us help to implement what I believe to be the fastest and most accurate search out there for our docs. 

So this is coming soon and fast!! 😎

**Comment by stabildev** [comment]
cmd + k search would be nice!

**Comment by micheleriva** [comment]
@stabildev we're on it :)
