### ISSUE TITLE
Build an App with Solid [Tutorial]

### ISSUE THREAD

**Issue by Jutanium** [solidjs/solid-docs-next#43]
Assumes knowledge of the core framework. Teaches how to build an SPA and why Solid Start makes that easier. 
Covers:
- Picking a styling method
- Understanding Vite
- Solid-app-router
- Code splitting
- Adding solid-start to an existing project (convergence point with SolidStart docs)

Ideally, this is an interactive tutorial that uses Vite in the browser with Stackblitz. @modderme123 and @nksaraf are looking into that infrastructure.

**Comment by vanillacode314** [comment]
I am looking into writing an article on how I built my first solid-start app? Maybe instead of writing it as an article I can contribute to docs? Would that be possible?

**Comment by michaelessiet** [comment]
> I am looking into writing an article on how I built my first solid-start app? Maybe instead of writing it as an article I can contribute to docs? Would that be possible?

At the moment we have completely different docs for Solid-Start. But you can contribute to these docs in other ways through sharing your experiences with Solid and sharing anything that you think anyone new to Solid should know
