### ISSUE TITLE
[FEAT] Add primitives into core docs

### ISSUE THREAD

**Issue by LadyBluenotes** [solidjs/solid-docs-next#438]
The Solid ecosystem has a lot of primitives that are useful to the users. We need to find a way to include them into the core docs so people don't need to sift through the READMEs of each to figure out how to use them or, in some cases, that they even exist.

**Comment by dyyyl** [comment]
I'm happy to pick this up - quick confirmation to get started, is this a complete list of current Solid primitives?

- `createSignal`
- `createEffect`
- `createMemo`
- `createResource`
- `createRoot`
- `createRenderEffect`
- `createDeferred`
- `createComputed`
- `createContext`
- `createMutable`
- `createStore`

**Comment by LadyBluenotes** [comment]
> I'm happy to pick this up - quick confirmation to get started, is this a complete list of current Solid primitives?
> 
> * `createSignal`
> * `createEffect`
> * `createMemo`
> * `createResource`
> * `createRoot`
> * `createRenderEffect`
> * `createDeferred`
> * `createComputed`
> * `createContext`
> * `createMutable`
> * `createStore`

This is mostly to be used as a reminder that we need to figure out a way to add the ecosystem primitives for visibility! So ones that are found at https://www.solidjs.com/ecosystem.

What you could do (if you'd like), is following a similar format to what we did with the Router, and adding all the store utilities to the references section on their own pages (https://www.solidjs.com/docs/latest/api#store-utilities).

I can create an issue for that and you can claim it there!

**Comment by dyyyl** [comment]
> I can create an issue for that and you can claim it there!

Sounds good, excited to get started ^_^

Does there yet exist a 'way of working' type doc (other than CONTRIBUTING.md) that we can reference to differentiate reminder type issues from issues that will be referenced in PR? I'm a bit out of my element and don't understand the preferred patterns on this project yet, but would like to become more familiar!

**Comment by LadyBluenotes** [comment]
> > I can create an issue for that and you can claim it there!
> 
> Sounds good, excited to get started ^_^
> 
> Does there yet exist a 'way of working' type doc (other than CONTRIBUTING.md) that we can reference to differentiate reminder type issues from issues that will be referenced in PR? I'm a bit out of my element and don't understand the preferred patterns on this project yet, but would like to become more familiar!

At the moment, not so much. In the future we'll be making more use of the `help-needed` tag, however. And we will make sure to post any open issues up for grabs in the `docs` channel!
