### ISSUE TITLE
Add i18n support 

### ISSUE THREAD

**Issue by danieljcafonso** [solidjs/solid-docs-next#441]
Right now, the docs only support `en-us` and have no support for any other type of language nor the mechanism implemented for when we have the translations. We need to understand how we would add i18n support and set up a process for it

**Comment by atilafassina** [comment]
I'd like to work on this! 
@LadyBluenotes

**Comment by LadyBluenotes** [comment]
Need to consider RTL as per #378

**Comment by LadyBluenotes** [comment]
@atilafassina is this good to close now?

**Comment by LadyBluenotes** [comment]
nvm i think it is lol #494
