### ISSUE TITLE
Vite Guide [How-To Guide]

### ISSUE THREAD

**Issue by Jutanium** [solidjs/solid-docs-next#46]
A self-contained guide answering the question: "How do I set up Vite for Solid from scratch?"
Includes Typescript setup and explains how Vite plugins work.

**Comment by JessicaSachs** [comment]
I'm gonna ask the Vite core team member that last closed the issue (👋🏻 @Shinigami92) if the maintenance burden wouldn't be too high at this point. No harm in asking a while later 🙏🏻. https://github.com/vitejs/vite/issues/5572

**Comment by Shinigami92** [comment]
I checked the downloads per week and they are to less
I won't say a min value here for now and need to ask the team, but for now: yes please use this extra step
