### ISSUE TITLE
Docs: Possible accessibility issues with the new light theme

### ISSUE THREAD

**Issue by dmitriid** [solidjs/solid-docs-next#469]
Originated here: https://twitter.com/dmitriid/status/1757703809441181927

Current light theme in the docs beta:

<img width="2405" alt="image" src="https://github.com/solidjs/solid-docs-next/assets/32768/2dfaa1ed-208a-4395-bf37-8802e6728dc4">

Most of the description below is subjective except one:

# Objective measurements

The colors in the left menu fail contrast requirements:

![image](https://github.com/solidjs/solid-docs-next/assets/32768/2661d262-52b0-4b3f-ad24-cd45beed7d15)

# Subjective:

It feels to me that it might be too hard on the eyes due to a rather small thing font on a rather dark background. My feeling is that having black-on-white would serve the page better.

This is made somewhat worse by even darker backgrounds (and sometimes smaller fonts) in other places on the page:

**Inline code**

<img width="696" alt="image" src="https://github.com/solidjs/solid-docs-next/assets/32768/0e45f0c2-3f91-4658-a7e2-45e96654c46c">

**Code lists**

<img width="615" alt="image" src="https://github.com/solidjs/solid-docs-next/assets/32768/5d02f92b-f068-43e7-a41d-b78b7305dea2">

**Asides**

<img width="720" alt="image" src="https://github.com/solidjs/solid-docs-next/assets/32768/12b2238a-ef35-4ed6-bb72-a2bc7cfb02eb">

Note: these are all rather subjective, so other people might have a different opinion.

**Comment by at-the-vr** [comment]
Hey Dmitri, the subjective concerns mentioned here target the [code component](https://github.com/solidjs/solid-docs-next/blob/main/src/ui/markdown-components.tsx#L199C3-L206C5) and I have jotted down couple of todos you can pitch in:
1. should font size for code component be larger?
2. any kind of code component has an associated background else its indistinguishable from plain text - [MDN Reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/code) that being said will lightening the background color for the same code component help the cause?

Let me know if you like one option or both of them 😄

**Comment by LadyBluenotes** [comment]
Hi @dmitriid & @at-the-vr,

I appreciate the incentive to work on styling of the site and improve it! Your time and effort is noticed and appreciated. 

For the time being, we are going to leave the site styling alone unless there are large, glaring things that need to be fixed. We are going to be having an accessibility audit to really get an understanding of how we can improve for the community and, while we appreciate the subject points of view, we want to focus more on the content than the styling of the site (again, unless there are important accessibility concerns that need to be addressed).

Thank you again for your time!
