### ISSUE TITLE
[chore] Organize content by breaking up sections into separate pages

### ISSUE THREAD

**Issue by LadyBluenotes** [solidjs/solid-docs-next#479]
The Deployment options & styling your components sections need to be broken up to avoid lengthy pages.

This issue will require the following:
- [ ] Creating a folder with the respective pages
- [ ] Creating a component that will link out the new pages that includes a logo of the respective section (ie. Netlify with deployment docs)

**Comment by LadyBluenotes** [comment]
Support from @atilafassina and @danieljcafonso on this :))

**Comment by danieljcafonso** [comment]
For point two on the check list we could make use of the `image-links` component. It works exactly for this use case
