### ISSUE TITLE
[content] Add "Comparison with FRAMEWORK" articles to new docs

### ISSUE THREAD

**Issue by dyyyl** [solidjs/solid-docs-next#485]
Add "Comparison with FRAMEWORK" articles to new docs, similar to this archived copy of a [Comparison to React](https://web.archive.org/web/20230521050706/https://docs.solidjs.com/guides/how-to-guides/comparison/react).

Some articles will have to be reworked to reflect [WRITING.md](https://github.com/solidjs/solid-docs-next/blob/main/WRITING.md) style guide.

**Comment by dyyyl** [comment]
These articles previously lived under the `guides/how-to-guides/comparison/react|angular|etc` routes. 

I think it would make sense to move these out of `how-to-guides` and into `concepts/comparison/react|angular|etc` routes.

Previous docs were removed [here](https://github.com/solidjs/solid-docs-next/commit/1a197f31395447c848ce4f92225638941b29b70f#diff-603a821e39040d4670ce36e0ec91aa3c990d8fda0c51f60ca4c28f5d03f6b5ea), and we can draw a lot of inspiration from those files.

**Comment by LadyBluenotes** [comment]
Hi @dyyyl, thanks for the suggestion. 

In the future when you have suggestions like this do you mind sharing them in the docs channel of the discord prior to creating an issue? 

These types of things require more of a discussion with the community and team. Issues like this shoukd ideally be treated as things that are planned or require attention versus as suggestions 🙂

**Comment by dyyyl** [comment]
Can do! Just to confirm that I have this correct: communication regarding work is carried over discord, and issues are used as manifests of either WIP or planned but unrealized work?

**Comment by LadyBluenotes** [comment]
Yes, that's the gist of it
