### ISSUE TITLE
guides/state-management.mdx Issue

### ISSUE THREAD

**Issue by earslap** [solidjs/solid-docs-next#489]
First example of Derived State sets up squaredCount but never uses it, then talks about doubleCount being potentially inefficient instead which I think is a mistake. Then shows how to solve it with memo but uses squaredCount for it as intended. I think there was some confusion while writing the first example.

**Comment by marvin-j97** [comment]
I agree the examples are somewhat awkward and don't really highlight the difference between a derived signal and a memo enough.

---

The first example could be changed to just:

```jsx
import { createSignal } from "solid-js"

function Counter() {
  const [count, setCount] = createSignal(0)

  // Derived signal
  const squaredCount = () => {
    return count() * count()
  }

  const increment = () => {
    setCount(count() + 1)
  }

  return (
    <>
      <div>Current count: {count()}</div>
      <div>Squared count: {squaredCount()}</div>
      <button onClick={increment}>Increment</button>
    </>
  )
}
```

The second example could be something like in the current Solid tutorial:

```jsx
import { createSignal, createMemo } from 'solid-js';

function Counter() {
  const [count, setCount] = createSignal(10);

  const fib = createMemo(() => {
    return fibonacci(count());
  })

  const increment = () => {
    setCount(count() + 1)
  }

  return (
    <>
      <div>Current count: {count()}</div>

      {/* When count changes, fib is only computed once, but rendered 5 times */}
      <div>Have some Fibonacci numbers: {fib()} {fib()} {fib()} {fib()} {fib()}</div>
      <button onClick={increment}>Increment</button>
    </>
  );
}
```

@earslap Would this make more sense to you?

**Comment by earslap** [comment]
Thank you @marvin-j97 I think this makes sense.

**Comment by JasonHassold** [comment]
@atilafassina I'm going to work on this one since it doesn't look like anyone has taken it yet

**Comment by LadyBluenotes** [comment]
@JasonHassold I'll assign it to you then.
