### ISSUE TITLE
concepts/understanding-jsx.mdx Issue

### ISSUE THREAD

**Issue by klequis** [solidjs/solid-docs-next#499]
Dynamic data transfer: Props are important when using dynamic data. They let components react in real-time to changes, resulting in a responsive application.

It could be just where I'm coming from but I don't see what the word "transfer" adds to "Dynamic data". Perhaps "transfer" could be dropped or given context.

**Comment by titoBouzout** [comment]
Does this clarify the issue?

> - **Static props**:
  In Solid's JSX, static props are integrated directly into the HTML template as attributes. The template is cloned and used as is.

> - **Dynamic props**:
  Dynamic props rely on state, allowing the content or properties to be dynamic, such changing the styling of an element  in response to interactions within an application. Mostly expressed in the form of signals `value={value()}`.

> - **Data transfer**:
  Props are also used to fill components with data that comes from resources, like `createResource` calls.
  Resulting in a component that reacts in real-time to data changes.

**Comment by titoBouzout** [comment]
Thanks for input, change the phrase to the suggested one and also added a link to the createResource page, full changes in https://github.com/solidjs/solid-docs-next/pull/514/files
