### ISSUE TITLE
concepts/understanding-jsx.mdx Issue

### ISSUE THREAD

**Issue by klequis** [solidjs/solid-docs-next#500]
Expressions, whether fixed or dynamic, get applied in the order defined within the JSX.

This sequence works for a wide range of DOM elements. However, with elements like input types with type='range' - the order matters since it can influence the element's behavior.

---

As I read this: The above order (i.e., get applied in the order defined within the JSX), works most of the time but not with certain elements like `<input type="range" , ... />` where the order matters. 

In cases where the order matters, is Solid modifying the order to what it needs to be or must the user ensure the orders is correct?

**Comment by titoBouzout** [comment]
@klequis does this make it better? 

> Expressions, whether fixed or dynamic, get applied *in the order defined within the JSX*. This works for a wide range of DOM elements, but won't work with elements that require attributes to be defined in a special order, like input types with `type='range'`.

>  When order influence the element's behavior, users must define the expressions in the order that element expect.

see https://github.com/solidjs/solid-docs-next/pull/513
