### ISSUE TITLE
Improve look&feel Code-Blocks

### ISSUE THREAD

**Issue by atilafassina** [solidjs/solid-docs-next#502]
Recently (#490), @doeixd had some ideas to improve the UI around the code-blocks. Making it more cohesive with the general website looks.

<details><summary>current state</summary>

![code-blocks](https://github.com/solidjs/solid-docs-next/assets/2382552/d3102380-5900-4c38-8a92-b101d90130ca)

</details>

Patrick, I'd love you to port the code-block changes to it's own PR.

Let's:

- get rid of the black background like you did in your implementation
- be careful with horizontal scrollbars

if you have other ideas while you're at it, please let us know.

**Comment by LadyBluenotes** [comment]
Closed with #506
