### ISSUE TITLE
Dropdown Language Selector

### ISSUE THREAD

**Issue by atilafassina** [solidjs/solid-docs-next#504]
As #494 is merged, we can start having contributions to take content into different languages. At the moment, no UI navigation system is in place to allow user to move from one language to another.

## Acceptance Criteria
- [ ] discussed the design and ux **before opening a PR**
- [ ] works from root (`/`), but also on nested routes (`/pt-br/components/for`)
- [ ] `<head>` should have the `<link rel="alternate">` elements
- [ ] upon navigation, it uses the `replace` attribute persist a single locale in history for an entry

**Comment by doeixd** [comment]
I was looking at Astros dropdown and noticed that for their selector, they are not using a custom styled select component.

Is it worth it to use a custom drop down? Or should we also opt for using the platform's select?

Or should we try and roughly match the theme selector dropdown?

**Comment by LadyBluenotes** [comment]
@atilafassina @danieljcafonso is this still in progress?

**Comment by danieljcafonso** [comment]
I would say it is implemented but hidden for now.
