### ISSUE TITLE
concepts/components/props.mdx Issue border or shadow of code eleement has been cut

### ISSUE THREAD

**Issue by Caffeine19** [solidjs/solid-docs-next#505]
![image](https://github.com/solidjs/solid-docs-next/assets/108726581/5cafe7b0-33b7-4b9f-a21e-cb4e334421a6)

First, I wonder why use "box-shadow" rather than "border" to draw an element's border.
The border or shadow of the code element has been cut.
If you use border and set the box-size to border-box, this problem won't happen, I guess.

the easiest solution for this seemed to add some margin.

```css
element.style{
  margin:2px
}
```
And now it's fine.

![image](https://github.com/solidjs/solid-docs-next/assets/108726581/2f217807-fe6d-46af-80f8-5df9aed268cf)
![image](https://github.com/solidjs/solid-docs-next/assets/108726581/f467d2f6-0a55-48d1-a166-8f0b5bcd0f74)

**Comment by Caffeine19** [comment]
Sorry, I just understand that the border property may not work fine when set to 1.5px.

**Comment by JasonHassold** [comment]
@atilafassina this was fixed by my PR too I'm pretty sure
