### ISSUE TITLE
Migration Guides [How-To Guide]

### ISSUE THREAD

**Issue by Jutanium** [solidjs/solid-docs-next#52]
How to migrate from
- Vue
- Svelte
- React
- Angular

Some existing content [here](https://www.solidjs.com/guides/comparison).

**Comment by ddanielcruzz** [comment]
Starting to work on React migration guide.

**Comment by michaelessiet** [comment]
I made a PR for the Vue migration and comparison

**Comment by vanillacode314** [comment]
Starting to work on svelte migration guide
