### ISSUE TITLE
Thinking Solid

### ISSUE THREAD

**Issue by Jutanium** [solidjs/solid-docs-next#54]
Explaining Solid's API design philosophy. Points from [here](https://www.solidjs.com/guides/getting-started#think-solid), but heavily rework to be beginner-friendly:
- Declarative Data
- Vanishing Components
- Read/Write Segregation
- Simple is Better Than Easy

This will likely be in a special Concept page or a Foundation page.

**Comment by michaelessiet** [comment]
I added this to the docs in one of my commits. I also wrote it in a more beginner-friendly manner as well as provided examples. I think this issue should be good to close 🤔
