### ISSUE TITLE
[Bug]: Component page titles HTML escape special characters

### ISSUE THREAD

**Issue by JasonHassold** [solidjs/solid-docs-next#582]
### 📝 Issue Description

very minor issue with the page titles 

![image](https://github.com/solidjs/solid-docs-next/assets/25469167/4cd6d155-32d4-463d-af44-87ecb6a0aa7f)

### 📋 On which page(s) it occurs

Pages with component syntax as the names, example `<Suspense>`

### 🤔 Expected Behavior

Don't HTML escape special characters in the page titles

### 👀 Current Behavior

Special characters are HTML escaped versions

### 🖥️ Browser

Chrome 122

**Comment by atilafassina** [comment]
I can't reproduce that neither in Chrome, Safari, or Firefox...
my Chrome version is `Version 122.0.6261.112` as well

![Screenshot 2024-03-11 at 21 54 54](https://github.com/solidjs/solid-docs-next/assets/2382552/8216bdc8-fb31-4a35-8344-397d6586162f)

**Comment by JasonHassold** [comment]
Hmm well that's weird, I can still replicate it, maybe a Windows 11 issue. I tested on Firefox and I don't see the issue there

**Comment by JasonHassold** [comment]
@atilafassina also strange there are other differences 

Firefox
![image](https://github.com/solidjs/solid-docs-next/assets/25469167/254bac1e-01bc-434f-a477-054fef394525)

Chrome
![Uploading image.png…]()

**Comment by JasonHassold** [comment]
But the page source is the same

Firefox
![image](https://github.com/solidjs/solid-docs-next/assets/25469167/4035fafa-f41c-4c28-8177-8475b93c6029)

Chrome
![image](https://github.com/solidjs/solid-docs-next/assets/25469167/dabadf89-1096-40a8-992d-e83aa9666637)

**Comment by LadyBluenotes** [comment]
I can't reproduce it on Chrome, Firefox, or Edge and I'm on Windows 11.

**Comment by JasonHassold** [comment]
Ok it's gotta be one of my chrome extensions then, just tested in incognito and the issue isn't happening. Thanks for checking everyone!
