### ISSUE TITLE
Grammar:

### ISSUE THREAD

**Issue by Hopelezz** [solidjs/solid-docs-next#61]
The way this reads could be more concise (See boxed text). 

Text found here: [Building UI With Components](https://docs.solidjs.com/guides/getting-started-with-solid/building-ui-with-components)

- There's an error with 'you' instead of 'your'.
- When spelling out an acronym, it's clearer to capitalize expressed acronyms, such as "DOM" seen below.

> As we learned above, Solid components return JSX. JSX is an HTML-like syntax used in Solid JavaScript code to represent part of the Document Object Model (DOM). In our HelloWorld.jsx example above, we returned the following JSX from our component:

<img width="638" alt="image" src="https://user-images.githubusercontent.com/72772558/174654210-4f48b40c-72a2-48df-9d79-e7c5ed8c0117.png">

**Comment by Jutanium** [comment]
Closed by #69!
