### ISSUE TITLE
[Bug]: Orama search results are sometimes very long and unformatted

### ISSUE THREAD

**Issue by GiyoMoon** [solidjs/solid-docs-next#656]
### 📝 Issue Description

Sometimes, depending on the result, orama outputs very long and unformatted search results.

### 📋 On which page(s) it occurs

On all pages

### 🤔 Expected Behavior

The search results should always be shortened like this:
![image](https://github.com/solidjs/solid-docs-next/assets/36984337/58001000-5df9-4534-ab41-0cc74829e6a0)

### 👀 Current Behavior

Sometimes, depending on the result, orama outputs very long and unformatted search results. Here I'm searching for `few` and the results are a mess:
![image](https://github.com/solidjs/solid-docs-next/assets/36984337/2b981e66-f1a0-482e-bc84-10cc8cffaf92)

### 🖥️ Browser

Chromium Engine Version 123.0.6312.106

**Comment by atilafassina** [comment]
Orama searchbox does not have syntax highlighting for the results (the Summary AI feature does).

if it's not easy to have it on SearchBox, we could perhaps add a new entry to the entries frontmatter with a text-only description (no code-snippets).

Wdyt, @LadyBluenotes  / @SaraVieira ?

**Comment by SaraVieira** [comment]
I think this is on our side, we could add syntax highlights but honestly descriptions shouldn't have them, what about a trim to like 200 characters? What y'all think?

**Comment by GiyoMoon** [comment]
I think it would be best to exclude code snippets there. It also results in things like here where it actually renders an input and checkbox:
![image](https://github.com/solidjs/solid-docs-next/assets/36984337/e38a7690-8c43-48e9-8fd9-e4d26f1b1ee7)

**Comment by GiyoMoon** [comment]
It feels like some issue with the search algorithm, because usually the searched word is marked bold and here, the search query `few` doesn't even occur in the description text and it just results in a really large text that seems random. Perhaps a fuzzy search that behaves weirdly?

**Comment by SaraVieira** [comment]
Honestly this an awesome find, bad bug but incredible on how cursed it is either way lol

Gonna try to get a new release today that removes all the code snippets from the results

**Comment by SaraVieira** [comment]
Okay this PR https://github.com/solidjs/solid-docs-next/pull/660 fixes the code, I am now fixing the fact that these descriptions are way too long
