### ISSUE TITLE
[Bug]: Orama summary overflows

### ISSUE THREAD

**Issue by GiyoMoon** [solidjs/solid-docs-next#657]
### 📝 Issue Description

Long summaries lead to overflow.

### 📋 On which page(s) it occurs

On every page

### 🤔 Expected Behavior

The modal should overflow-scroll if the summary is too big.

### 👀 Current Behavior

It overflows and messes with the footer.
![image](https://github.com/solidjs/solid-docs-next/assets/36984337/53245be8-b297-4376-a5aa-4d4eabbddf2a)

### 🖥️ Browser

Chromium Engine Version 123.0.6312.106

**Comment by atilafassina** [comment]
This is an issue on Orama's official searchbox component. So I think it's unlikely we'll be able to fix it within the docs app.

---

I'll ping @micheleriva , @saravieira, and perhaps also @jer3m01

**Comment by SaraVieira** [comment]
Yes! I am on it!

Thank you for the issue
