### ISSUE TITLE
Seperate out infratructure code and documentation content

### ISSUE THREAD

**Issue by crutchcorn** [solidjs/solid-docs-next#66]
# The problem

Currently, we're using file-based routing for our blog posts in order to define URL routing.

This leads to a problem where in order to find any given content, we have to navigate into:

```
src/routes/guides
```

Which is intermingled with source code and can be challenging to find for newcomer contributors that intend on solely contributing to our docs, and not our infrastructure codebase.

# The solution

Per a discussion I had with @Jutanium, we would like to move to something of a similar model that I use for the [Unicorn Utterances](https://unicorn-utterances.com) codebase where [we have split root folders for these](https://github.com/unicorn-utterances/unicorn-utterances/), like so:

- `src` - Where our infrastructure code lives
- `content` - Where our blog posts/documentation/etc lives

This means that in order to do this, we need to move away from file-based routing, and toward parameter-based routing.

I've started a WIP example branch here:

https://github.com/solidjs/solid-docs-next/tree/co-locate-guides

## Hiccups in implementation

You'll notice that if you attempt to run the code in my branch, it will fail. This is because, as I understand it, the current codebase:

- [Uses Vite to compile MDX and MD files down to TSX file equivalents](https://github.com/solidjs/solid-docs-next/blob/co-locate-guides/vite.config.ts#L26-L65)
- Which then uses file-based routing in order to define the page URI

However, because our Vite plugin compiles MDX files to a function, this does not work. AFAIK, `solid-start` has the same limitations as NextJS's `getServerSideProps` in terms of required serialization going from the server to the client via `routeData`

In order to solve for this problem, I've previously (for UU, which uses NextJS):

1) [Read the markdown files into a string](https://github.com/unicorn-utterances/unicorn-utterances/blob/main/src/pages/posts/%5B...postInfo%5D.tsx#L242-L245)
2) On the server, [run an initial `rehype` instance in order to add some specific plugins and transformations](https://github.com/unicorn-utterances/unicorn-utterances/blob/05a393f13970f7ec933bd2e049659cb92f05ebc2/src/utils/markdown/markdownToHtml.ts#L51-L101)
3) [Passed that string to the client](https://github.com/unicorn-utterances/unicorn-utterances/blob/main/src/pages/posts/%5B...postInfo%5D.tsx#L253)
4) Then on the client [re-initialized the HTML string using `rehype`](https://github.com/unicorn-utterances/unicorn-utterances/blob/05a393f13970f7ec933bd2e049659cb92f05ebc2/src/utils/markdown/useMarkdownRenderer.tsx#L61-L71)
5) Finally, took that [AST and mapped it back to React (or in our case, Solid) components](https://github.com/unicorn-utterances/unicorn-utterances/blob/05a393f13970f7ec933bd2e049659cb92f05ebc2/src/utils/markdown/useMarkdownRenderer.tsx#L34-L52)

This leads to a problem where our initial hydration of the page leads to duplicate data between the HTML passed to the client and the HTML that our second `rehype` instance runs into.

It's unclear what the best decision of overcoming this implementation detail would be. Advice/guidance would be greatly appreciated.

Once a decision is made on what to do next, I'm happy to work on the code to make this a reality.

**Comment by michaelessiet** [comment]
Issue has been addressed and implemented. Thanks to all the contributors
