### ISSUE TITLE
[Bug]: Unexpected "Get started" button behaviour

### ISSUE THREAD

**Issue by Tommypop2** [solidjs/solid-docs-next#672]
### 📝 Issue Description

The "Get started" button always navigates to `/quick-start`, regardless of the tab selected.

### 📋 On which page(s) it occurs

https://docs.solidjs.com/, https://docs.solidjs.com/solid-router, https://docs.solidjs.com/solid-start

### 🤔 Expected Behaviour

I would expect this button to navigate to the ["Getting Started"](https://docs.solidjs.com/solid-start/getting-started) page for Start, and to ["Routing in Solid"](https://docs.solidjs.com/solid-router/getting-started/installation-and-setup) when the Meta tab is selected

### 👀 Current Behaviour

The "Get started" button always navigates to `/quick-start`, regardless of the tab selected.

### 🖥️ Browser

Microsoft Edge Version 123.0.2420.81

**Comment by Tommypop2** [comment]
I'm happy to contribute a fix if this behaviour is unintended :)

**Comment by LadyBluenotes** [comment]
Thank you for noting this @Tommypop2 ! If you'd like, you're more than welcomed to tackle this :)

**Comment by Tommypop2** [comment]
@LadyBluenotes Just opened a PR :)
