### ISSUE TITLE
[Bug]: Orama summary keeps first result cached

### ISSUE THREAD

**Issue by GiyoMoon** [solidjs/solid-docs-next#673]
### 📝 Issue Description

The summary on the orama search never updates after the first result is loaded.

### 📋 On which page(s) it occurs

Every page

### 🤔 Expected Behavior

The summary should update when searching for a new phrase.

### 👀 Current Behavior

Here I'm searching for `context`, the summary loads and after it stays the same forever:

https://github.com/solidjs/solid-docs-next/assets/36984337/6706201c-8f15-4c3d-8c26-91acff23d01e

### 🖥️ Browser

Chrome

**Comment by GiyoMoon** [comment]
cc @SaraVieira

**Comment by SaraVieira** [comment]
Sorry for the delay, this was a bad one. No idea how I didn't catch this before honestly

Sorry about that, got a PR and will make one for here when a new version is out
