### ISSUE TITLE
[Content]:

### ISSUE THREAD

**Issue by keet5** [solidjs/solid-docs-next#697]
### 📚 Subject area/topic

/index.mdx

### 📋 Page(s) affected (or suggested, for new content)

https://docs.solidjs.com/concepts/control-flow/dynamic

### 📋 Description of content that is out-of-date or incorrect

When I import the Dynamic from solidjs, I have the error "Module '"solid-js"' has no exported member 'Dynamic'. But it works when I import from "solid-js/web".
![image](https://github.com/solidjs/solid-docs-next/assets/51784383/42677cdf-c973-4826-8c7f-cc97d4a8d2e1)
![image](https://github.com/solidjs/solid-docs-next/assets/51784383/cea8d9d0-656c-457e-b6f5-6d566f7b28ac)
![image](https://github.com/solidjs/solid-docs-next/assets/51784383/02188452-4b2e-4351-9d87-b45c599b8f05)

**Comment by LadyBluenotes** [comment]
Looks like this was addressed with #698 :) Thank you for flagging it!
