### ISSUE TITLE
[Other]: Make all titles sentence case

### ISSUE THREAD

**Issue by LadyBluenotes** [solidjs/solid-docs-next#704]
### 📋 Explain your issue

There is inconsistent title casing throughout the application. Rather than capitalizing all words, we're going to make sentence case the standard going forward. This means we have to go through the application and adjust all titles so that there are no other capitals in the headings, outside of the first letter of the first word.

**Comment by LDraco-Sharif** [comment]
Hi @LadyBluenotes, I have made a draft PR for this issue [here](https://github.com/solidjs/solid-docs-next/pull/709). Here, I tried to update all the titles I could find to sentence case.
