### ISSUE TITLE
Effects of changing the function name in the instructions

### ISSUE THREAD

**Issue by Hopelezz** [solidjs/solid-docs-next#72]
# Problem

When the user is instructed to change the name of the Function from App to Bookshelf this breaks the Rendered function. The name "App" is still referenced in the index.jsx.

<img width="413" alt="image" src="https://user-images.githubusercontent.com/72772558/175783463-71852462-2d95-499c-8942-2b20d3aad617.png">

This is then referenced by the index.html file. to generate the App.jsx file.

<img width="587" alt="image" src="https://user-images.githubusercontent.com/72772558/175783445-f44a77d7-bb78-40bd-917e-416c7070b672.png">

All this can be found on lines 280 - 293

<img width="622" alt="image" src="https://user-images.githubusercontent.com/72772558/175783731-b9b72a82-f77e-49f9-8f92-1932c1f8b8d2.png">

# Solution

I think in order for the user to build the app fully they should be instructed on a few steps before adjusting the Function name. At least to show the relationship of the files mentioned.

- Maybe an explanation section going over the files right after the installation of Solidjs.
    - If you do this you can add an aside pointing to the instructions on how to edit the other files.
- Walk through the steps of editing the additional files.

**Comment by crutchcorn** [comment]
Well, so this actually shouldn't break anything.

Because `App` is a default export and not a named one, you should be able to have your function and the imported name be different

**Comment by boehs** [comment]
I think this issue can be safely closed
