### ISSUE TITLE
Basics documentation has a wrong example on display 

### ISSUE THREAD

**Issue by Ryan-Zayne** [solidjs/solid-docs-next#751]
### 📚 Subject area/topic

/concepts/components/basics.mdx

### 📋 Page(s) affected (or suggested, for new content)

https://docs.solidjs.com/concepts/components/basics

### 📋 Description of content that is out-of-date or incorrect

The explanation of one of the examples specifies that it used the ternary operator for conditional rendering, when in fact it was the Show component that was used there

**Comment by LadyBluenotes** [comment]
Thanks for flagging this! I just updated it :)
