### ISSUE TITLE
Tone: Exclamation

### ISSUE THREAD

**Issue by Hopelezz** [solidjs/solid-docs-next#76]
# Problem:

Previous discussion with @Jutanium on tone within the Docs. It's not the responsibility of the Docs to provide hype.

# Solution:

Removing the exclamation mark on
src > routes > tutorials > getting-started-with-components.mdx
line: 184

*Great first issue*

![image](https://user-images.githubusercontent.com/72772558/175831031-a5558200-ccd2-418b-8a8b-f15dac43be53.png)

**Comment by chisom5** [comment]
# Hey I would like to resolve this issue.

**Comment by Hopelezz** [comment]
@chisom5 Hey awesome! Glad to help you if you need anything just let me know.

**Comment by Hopelezz** [comment]
@chisom5, I want to point out that when you referenced #76 in your commit it shows up here in the main project. You can submit a PR now. I suggest providing context to the PR by writing a few words regarding the submission. Super glad I had this opportunity to go over this with you.
