### ISSUE TITLE
table of contents doesn't autoscroll to page sections

### ISSUE THREAD

**Issue by kevinzunigacuellar** [solidjs/solid-docs-next#77]
__Description__
Let me start by saying fantastic job on the new docs page. It covers many more topics to get started with solid that a lot of people will find very helpful.

As promised my daily issue with the new docs page. 

- The content table to the page's right doesn't auto-scroll to the intended page section.
- I couldn't find a page regarding why solid and how is it different from other frameworks

**Comment by Yan-Thomas** [comment]
This is a nice UX improvement we can make, I'll take a look at the codebase and submit a PR for this! Thanks for pointing this out 🙌

**Comment by Yan-Thomas** [comment]
I have tried to fix this bug but it was related to SolidStart, which seems to have been fixed recently, so I think we can close this issue!
![image](https://i.imgur.com/nnLctSq.gif)
